### ISSUE TITLE
Salary Column

### ISSUE THREAD

**Issue by Ann1897** [thiyangt/DSjobtracker#10]
Is Salary column in USD yearly?? Or its the original column as previous without any changes?

**Comment by janithwanni** [comment]
Yes it is in yearly USD amounts. There is a bit of confusion with the variable descriptions. I will create a separate column with the yearly USD amount

**Comment by Ann1897** [comment]
No need to add a new column. I have used your column and fixed the issue

**Comment by janithwanni** [comment]
All good then. Thanks @Ann1897
