### ISSUE TITLE
The job title column needs to be cleared.

### ISSUE THREAD

**Issue by randishashikala** [thiyangt/DSjobtracker#11]
There are a few spelling mistakes & so many job titles in this column. So, I used the following R code to categorize the job title column.

#Identify job titles
Job_title_new <- str_to_lower(DStidy_2021$Job_title)
Job_title_new <- str_trim(Job_title_new)

## Rename misspelled names
Job_title_new[Job_title_new == "data engineera"] <- "data engineers"
Job_title_new[Job_title_new  %in% c("senior data enginner", "senior data engineeer")] <- "senior data engineers"

## Categorize jobs as data science, data analyst, data engineer

DS <- Job_title_new[grepl(c("data sci| machine| scientist"), Job_title_new)] 
DE <- Job_title_new[grepl(c("data engineer | engin| intelligence"), Job_title_new)]
DA <- Job_title_new[grepl(c("analy|statist|actuarial| research"), Job_title_new)]

DA <- DA %>% append(Job_title_new[!(Job_title_new%in%c(DS,DE,DA))] %>% unique() %>% .[str_detect(.,"data\\s+")])
DS <- DS %>% append(Job_title_new[!(Job_title_new%in%c(DS,DE,DA))] %>% unique() %>% .[str_detect(.,"machine\\s+")])

DA <- DA[!DA%in%DS] #DA Job titles not include in the Ds 
DA <- DA[!DA%in%DE] #DA Job titles not include in the DE
DS <-DS[!DS%>%is.na()] 
DE <-DE[!DE%>%is.na()]
Others <- Job_title_new[!(Job_title_new%in%c(DS,DE,DA))] %>% unique()

data <- DStidy_2021 %>% mutate(Job_Category = ifelse(Job_title_new%in%DS & Job_title_new%in%DE, "Data Science & Data Engineering", ifelse(Job_title_new%in%DS, "Data Science", ifelse(Job_title_new%in%DE, "Data Engineering", ifelse(Job_title_new%in%DA,"Data Analyst", "Others")))))

**Comment by janithwanni** [comment]
Hi Randi, 
Thanks for the cleaning code. I will add these to the cleaning script and let you know ASAP.

**Comment by janithwanni** [comment]
I pushed your code to the cleaning script. Can you check whether it's working now @randishashikala ?

**Comment by randishashikala** [comment]
Thank you Janith. It is working now.
