### ISSUE TITLE
Locations need to cleaned

### ISSUE THREAD

**Issue by rashminiR** [thiyangt/DSjobtracker#9]
The country names of the location variable need to cleaned, there are duplicate names, country names with cities, etc.

I'm sharing the code I used to clean the raw dataset, for reference.
#Country
df$Location <- replace(df$Location, c(127:129), "Australia" )
df$Location <- replace(df$Location, c(108, 110, 282, 297, 300, 302), "Sri Lanka" )
df$Location <- replace(df$Location, c(25:27, 117,131,273:279,308,310:314,370,375), "UK"  )

df <- df %>%
  mutate(Country = case_when(df$Location == "Australia" ~ "Australia",
                             df$Location == c("Canada", "canda", "canada") ~ "Canada",
                             df$Location == "France" ~ "France",
                             df$Location == "New Zealand" ~ "New Zealand",
                             df$Location == "Spain" ~ "Spain",
                             df$Location == "Sweden" ~ "Sweden",
                             df$Location == c("Pennsylvania","USA") ~ "United States",
                             df$Location == c("Bengaluru, Karnataka, India", "India") ~ "India",
                             df$Location == "Russia" ~ "Russia",
                             df$Location == "Sri Lanka" ~ "Sri Lanka",
                             df$Location == "UAE" ~ "United Arab Emirates",
                             df$Location == "China" ~ "China",
                             df$Location == "Ireland" ~ "Ireland",
                             df$Location == "Philippines" ~ "Philippines",
                             df$Location == "Singapore" ~ "Singapore",
                             df$Location == "UK" ~ "United Kingdom",
                             TRUE   ~  "Sri Lanka"    )) 

df$Country <- replace(df$Country, c(71, 74, 140, 141, 143:173, 266:270, 368, 369),"Canada")  
df$Country <- replace(df$Country, c(104, 105, 122, 124:126, 177:179, 256:265),"India") 
df$Country <- replace(df$Country, c(1, 3:6, 9:20, 28:35, 89:91, 100:103, 106:109, 119, 121, 123, 132, 133, 174, 245, 280, 281, 350, 360:363, 371:374),"United States")  

df$country_code <- countryname(df$Country, destination = 'iso3c')

**Comment by janithwanni** [comment]
Hi Rashmini,
Where did the countryname function come from? I haven't come across that function yet. Can you tell me the package that you used for it.

**Comment by rashminiR** [comment]
It's from the countrycode package

**Comment by janithwanni** [comment]
Thanks. I will fix this issue and create a PR for it.

**Comment by janithwanni** [comment]
Can you check now @rashminiR ?

**Comment by rashminiR** [comment]
All good! Thanks @janithwanni
